package common

import (
	"fmt"
	"strings"
	"sync"
	"time"
)

// URL represents a universal resource locator string.
type URL string

// DeviceName represents the name of an audio or system device.
type DeviceName string

// Address represents a network address string.
type Address string

// Span represents a named duration of time for performance tracking.
type Span struct {
	Name     string
	Duration time.Duration
}

// Spans is a first-class collection for performance spans.
type Spans []Span

// PerformanceMetrics is a first-class collection for performance spans.
type PerformanceMetrics struct {
	mutex sync.Mutex
	data  Spans
}

// Add appends a new span to the metrics.
func (metrics *PerformanceMetrics) Add(name string, duration time.Duration) {
	if metrics == nil {
		return
	}
	metrics.mutex.Lock()
	defer metrics.mutex.Unlock()
	metrics.data = append(metrics.data, Span{Name: name, Duration: duration})
}

// Summary returns a string representation of the performance metrics.
func (metrics *PerformanceMetrics) Summary() string {
	if metrics == nil {
		return "No metrics available"
	}
	metrics.mutex.Lock()
	defer metrics.mutex.Unlock()

	var summaryBuilder strings.Builder
	var totalDuration time.Duration
	for _, span := range metrics.data {
		summaryBuilder.WriteString(fmt.Sprintf("%s=%v ", span.Name, span.Duration.Round(time.Millisecond)))
		totalDuration += span.Duration
	}
	return fmt.Sprintf("TOTAL: %v [%s]", totalDuration.Round(time.Millisecond), strings.TrimSpace(summaryBuilder.String()))
}

// Profile wraps PerformanceMetrics to provide a cleaner interface.
// Structs must have no more than 2 instance variables.
type Profile struct {
	Metrics *PerformanceMetrics
}

// NewProfile creates a new Profile with initialized PerformanceMetrics.
func NewProfile() *Profile {
	return &Profile{
		Metrics: &PerformanceMetrics{
			data: make(Spans, 0),
		},
	}
}

// AddSpan adds a span to the profile's metrics.
func (profile *Profile) AddSpan(name string, duration time.Duration) {
	if profile == nil {
		return
	}
	profile.Metrics.Add(name, duration)
}

// Summary returns the summary of the profile's metrics.
func (profile *Profile) Summary() string {
	if profile == nil {
		return "No profile data"
	}
	return profile.Metrics.Summary()
}

// Language represents the language codes used in the system.
type Language string

const (
	LanguageEnglish    Language = "en"
	LanguagePortuguese Language = "pt"
)

// Transcription represents the textual representation of speech.
type Transcription string

// LLMResponseContent represents the text generated by a language model.
type LLMResponseContent string

// SpeechEntry is a container for speech data and its context.
type SpeechEntry struct {
	Details SpeechDetails
	Context EntryContext
}

// EntryContext provides metadata for entries passing through the system.
type EntryContext struct {
	Timestamp time.Time
	Profile   *Profile
}

// SpeechDetails contains the core data of a speech transcription or the raw audio data for multimodal processing.
type SpeechDetails struct {
	Text     Transcription
	Language Language
	Audio    []byte
}

// LLMEntry is a container for language model output and its context.
type LLMEntry struct {
	Chunk   LLMChunk
	Context EntryContext
}

// LLMChunk represents a portion of a language model response.
type LLMChunk struct {
	Details LLMDetails
	Done    bool
}

// LLMDetails contains the text and language of a language model chunk.
type LLMDetails struct {
	Text          LLMResponseContent
	InputLanguage Language
}

// SpeechChannel is a channel for passing SpeechEntry objects.
type SpeechChannel chan SpeechEntry

// LLMChannel is a channel for passing LLMEntry objects.
type LLMChannel chan LLMEntry
